### ISSUE TITLE
BFS ArrayOutOfBoundsExcept level 3

### ISSUE THREAD

**Issue by smc395** [smc395/Sliding-Brick-Puzzle#18]
When performing bfs on level 3 of sliding brick puzzle, ArrayOutOfBoundsExcept occurs for some reason.

**Comment by smc395** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at Game.listAllPieceMoves(Game.java:208)
    at Game.listAllMoves(Game.java:292)
    at Game.bfsearch(Game.java:348)
    at Game.bfs(Game.java:319)
    at HW2.main(HW2.java:58)

I think it's because I don't account for pieces that are greater than 2 tiles

**Comment by smc395** [comment]
Issuse was not due to normalizing at the wrong location. Not this bug.
